name: Generate Quiz Index

on:
  push:
    branches: [ main ]
    paths:
      - 'quiz/**/*.json'
      - 'scripts/generateIndex.ts'
      - 'scripts/generateAllJson.ts'
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate index and all.json files
        run: |
          WORKSPACE=${{ github.workspace }} bun scripts/generateIndex.ts
          WORKSPACE=${{ github.workspace }} bun scripts/generateAllJson.ts

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json quiz/**/all.json
          git commit -m "🤖 Auto-update quiz index and all.json files"
          git push
